### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by CHP314** [LeoHsiao1/pyexiv2#102]
Hello 

I try to run this simple code

import pyexiv2

with pyexiv2.Image(r'test.jpg') as img:
    data = img.read_exif()
    print(data)

and I get the following error: 
Traceback (most recent call last):
  File "/Volumes/Cle 32Go/Image Manip/imagePyexiv2.py", line 1, in <module>
    import pyexiv2
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyexiv2/__init__.py", line 6, in <module>
    from .core import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyexiv2/core.py", line 1, in <module>
    from .lib import exiv2api
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyexiv2/lib/__init__.py", line 25, in <module>
    ctypes.CDLL(os.path.join(lib_dir, 'libexiv2.dylib'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyexiv2/lib/libexiv2.dylib, 6): image not found

I run it on a macBookAir with El Capitan 10.11.6. 
Usually my python scripts run (slowly but run). 
I've tried several paths even if my file is in the same folder than the script. 

Thank you for your help. 
H.

**Comment by LeoHsiao1** [comment]
Hi, you have a compatibility problem.
You can try this solution in the tutorial:
<https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md#faq>

**Comment by CHP314** [comment]
Hi, 
Thank you for your quick answer. 
I’m going to try this one. 

And as usual :
Read the doc first. 

H. 


Envoyé de mon iPhone
