### ISSUE TITLE
issues on mac m1

### ISSUE THREAD

**Issue by nitishsaDire** [LeoHsiao1/pyexiv2#108]
Hey, I have built as per build instructions for Darwin. https://github.com/LeoHsiao1/pyexiv2/tree/master/pyexiv2/lib
Build was successful as it generated exiv2api.so file. But when I import pyexif2 it is giving following error.

```
>>> import pyexiv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tsm/Downloads/thumbnail_experiments/pyexiff/pyexiv2/pyexiv2/__init__.py", line 6, in <module>
    from .core import *
  File "/Users/tsm/Downloads/thumbnail_experiments/pyexiff/pyexiv2/pyexiv2/core.py", line 4, in <module>
    from .lib import exiv2api
  File "/Users/tsm/Downloads/thumbnail_experiments/pyexiff/pyexiv2/pyexiv2/lib/__init__.py", line 25, in <module>
    import exiv2api
ImportError: dlopen(/Users/tsm/Downloads/thumbnail_experiments/pyexiff/pyexiv2/pyexiv2/lib/py3.8-darwin/exiv2api.so, 0x0002): symbol not found in flat namespace '__ZN5Exiv210BasicErrorIcE6setMsgEv'
```

Thanks in advance

**Comment by LeoHsiao1** [comment]
Hi, exiv2 is currently released as a pre-compiled package for the AMD64 platform via GitHub Action. If you are using it on ARM64 platform, you need to compile exiv2 manually, which requires C++ knowledge and some difficulty. Sorry I'm not familiar with C++ either.
https://github.com/Exiv2/exiv2/issues/2173

After compiling exiv2 successfully, it is time to compile pyexiv2.

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by richardthegit** [comment]
Thanks @LeoHsiao1 ! 
This is working for me on an M3 mac, however there were other dependencies: brotli and gettext. I.e.:

`brew install inih gettext brotli`

I guess these are pretty commonly installed as I must have already had them on my dev machine, but weren't present on a clean production machine.
