### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by kyla2** [LeoHsiao1/pyexiv2#14]
Traceback (most recent call last):
  File "/home/py/PycharmProjects/SphinxDoc/_test/md_album.py", line 283, in <module>
    from pyexiv2 import Image
  File "/home/py/anaconda3/envs/py35/lib/python3.5/site-packages/pyexiv2/__init__.py", line 6, in <module>
    from .core import *
  File "/home/py/anaconda3/envs/py35/lib/python3.5/site-packages/pyexiv2/core.py", line 2, in <module>
    from .lib import exiv2api as api
  File "/home/py/anaconda3/envs/py35/lib/python3.5/site-packages/pyexiv2/lib/__init__.py", line 19, in <module>
    ctypes.CDLL(os.path.join(lib_dir, 'libexiv2.so')) # import the library at first, otherwise the Python interpreter can not find it.
  File "/home/py/anaconda3/envs/py35/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/py/anaconda3/envs/py35/lib/python3.5/site-packages/pyexiv2/lib/libexiv2.so)

**Comment by LeoHsiao1** [comment]
GLIBC is a C library.
You need to install the newer version of GLIBC, or upgrade your Linux system.
Refer to [this question](https://stackoverflow.com/questions/59145051/glibc-2-27-not-found-ubuntu-16-04).
