### ISSUE TITLE
Read exif crashes on a file with ê in title

### ISSUE THREAD

**Issue by djotaku** [LeoHsiao1/pyexiv2#15]
crashes with UnicodeDecodeError

**Comment by LeoHsiao1** [comment]
Please show me the full error information.
If you send that picture to my email, <leohsiao@foxmail.com>, I can try it.

**Comment by djotaku** [comment]
Full stack trace is: 
Traceback (most recent call last):
  File "/home/ermesa/Programming Projects/python/photo_stats/photostats/__main__.py", line 24, in <module>
    main()
  File "/home/ermesa/Programming Projects/python/photo_stats/photostats/__main__.py", line 18, in main
    exif = get_exif.get_exif(photos)
  File "/home/ermesa/Programming Projects/python/photo_stats/photostats/get_exif.py", line 48, in get_exif
    this_image_exif = this_image.read_exif()
  File "/home/ermesa/Programming Projects/python/photo_stats/venv/lib64/python3.7/site-packages/pyexiv2/core.py", line 37, in read_exif
    return self._parse(self._exif, encoding)
  File "/home/ermesa/Programming Projects/python/photo_stats/venv/lib64/python3.7/site-packages/pyexiv2/core.py", line 64, in _parse
    decoded_line = [i.decode(encoding) for i in line]
  File "/home/ermesa/Programming Projects/python/photo_stats/venv/lib64/python3.7/site-packages/pyexiv2/core.py", line 64, in <listcomp>
    decoded_line = [i.decode(encoding) for i in line]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 6: invalid continuation byte

photo can be downloaded from:    https://www.dropbox.com/s/81ppdbk02on1iok/2020%20Tet%20Family%20Portrait.jpg?dl=0

**Comment by LeoHsiao1** [comment]
The metadata of the image you uploaded has been erased. So that it can not be read. 

Based on your error message, I suggest you try different encoding formats, like this:
```python
this_image.read_exif(encoding='utf-8')
this_image.read_exif(encoding='iso-8859-1')
```

**Comment by LeoHsiao1** [comment]
Does that solve your problem?

**Comment by djotaku** [comment]
Sorry, got a little busy because of COVID.

Yes, that fixes the problem. Thanks!

**Comment by LeoHsiao1** [comment]
Hope you are ready to defend against the Covid-19 and the chaos it brings.
Wish you health and safety.
